/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
minify_jpeg_1(jpeg arg1, jpeg *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, MINIFY_JPEG,
		(xdrproc_t) xdr_jpeg, (caddr_t) &arg1,
		(xdrproc_t) xdr_jpeg, (caddr_t) clnt_res,
		TIMEOUT));
}
