/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct jpeg {
	struct {
		u_int image_len;
		char *image_val;
	} image;
};
typedef struct jpeg jpeg;

#define MINIFY_PROG 0x20000001
#define MINIFY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFY_JPEG 1
extern  enum clnt_stat minify_jpeg_1(jpeg , jpeg *, CLIENT *);
extern  bool_t minify_jpeg_1_svc(jpeg , jpeg *, struct svc_req *);
extern int minify_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFY_JPEG 1
extern  enum clnt_stat minify_jpeg_1();
extern  bool_t minify_jpeg_1_svc();
extern int minify_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_jpeg (XDR *, jpeg*);

#else /* K&R C */
extern bool_t xdr_jpeg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
